service: event-destinations

provider:
  name: aws
  runtime: python3.8

functions:
  importantFunction:
    handler: handler.starting
    destinations:
      onFailure: "arn:aws:sns:us-east-1:560654602687:myEventDestinationTopic"
